# -*- coding: utf-8 -*-
"""dubai_whale_watcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_VMb7OeYeD-iijZmnzmmIZuzuMmFLWQR
"""

# ==========================================
# PROJECT: DUBAI WHALE WATCHER (v1.1 - The Hunter)
# ARCHITECTURE: 5-Layer Vector Radar + XGBoost
# ==========================================

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, recall_score

import warnings
warnings.filterwarnings('ignore')

# ---------------------------------------------------------
# LAYER 1 & 2: THE MATRIX (Simulator - Persistent Property Fix)
# ---------------------------------------------------------
class DubaiWealthSimulator:
    def __init__(self, num_users=9900, days=365):
        self.num_users = num_users
        self.days = days
        self.start_date = datetime(2025, 3, 22)
        self.states = ['normal', 'emerging', 'active_whale', 'anchored_whale', 'exit_risk']
        self.transitions = {
            'normal': {'normal': 0.94, 'emerging': 0.05, 'exit_risk': 0.01},
            'emerging': {'emerging': 0.80, 'active_whale': 0.15, 'normal': 0.05},
            'active_whale': {'active_whale': 0.70, 'anchored_whale': 0.25, 'exit_risk': 0.05},
            'anchored_whale': {'anchored_whale': 0.95, 'exit_risk': 0.05},
            'exit_risk': {'exit_risk': 0.90, 'normal': 0.10}
        }

    def generate_data(self):
        data, user_metadata = [], []
        for user_id in range(self.num_users):
            current_state = np.random.choice(self.states, p=[0.7, 0.2, 0.05, 0.03, 0.02])
            whale_start_t = None

            for day in range(self.days):
                date = self.start_date + timedelta(days=day)

                prev_state = current_state
                current_state = np.random.choice(list(self.transitions[prev_state].keys()), p=list(self.transitions[prev_state].values()))

                if current_state in ['active_whale', 'anchored_whale'] and whale_start_t is None:
                    whale_start_t = date

                if np.random.rand() < 0.25: # Slightly reduced noise
                    data.append(self._create_event(user_id, date, 'lifestyle_noise', np.random.uniform(50, 300)))

                if current_state == 'emerging' and np.random.rand() < 0.10:
                    for _ in range(np.random.randint(1, 4)):
                        data.append(self._create_event(user_id, date, 'crypto_offramp', np.random.uniform(20000, 80000)))

                elif current_state in ['active_whale', 'anchored_whale']:
                    # CHATGPT FIX: Persistent, structured property behavior
                    if np.random.rand() < 0.02:
                        data.append(self._create_event(user_id, date, 'property_acq', 250000))
                    if np.random.rand() < 0.04:
                        data.append(self._create_event(user_id, date, 'property_commitment', 50000))

                    if current_state == 'active_whale' and np.random.rand() < 0.05:
                        data.append(self._create_event(user_id, date, 'luxury_retail', np.random.uniform(10000, 50000)))

                if current_state == 'anchored_whale':
                    if date.day == 1:
                        data.append(self._create_event(user_id, date, 'residency_anchor', 45000))

                elif current_state == 'exit_risk':
                    exit_intensity = min(0.02 + (day / self.days) * 0.15, 0.20)
                    if np.random.rand() < exit_intensity:
                        data.append(self._create_event(user_id, date, 'wealth_flight', np.random.uniform(50000, 150000)))

            user_metadata.append({
                'user_id': user_id,
                'whale_since': whale_start_t,
                'is_high_value': current_state in ['active_whale', 'anchored_whale']
            })

        return pd.DataFrame(data), pd.DataFrame(user_metadata)

    def _create_event(self, user_id, date, event_type, amount):
        return {'user_id': user_id, 'timestamp': date, 'event_type': event_type, 'amount': round(amount, 2)}

# ---------------------------------------------------------
# LAYER 3 & 4: THE VECTOR RADAR (Clean Delta Fix)
# ---------------------------------------------------------
DECAY = {"crypto": 0.05, "property": 0.005, "lifestyle": 0.08, "anchor": 0.003, "exit": 0.07}
BUCKET_MAP = {
    "crypto_offramp": "crypto", "property_acq": "property", "property_commitment": "property",
    "luxury_retail": "lifestyle", "lifestyle_noise": "lifestyle",
    "residency_anchor": "anchor", "wealth_flight": "exit"
}

def compute_vector_score(df):
    df = df.sort_values(["user_id", "timestamp"])
    history = []

    for user_id, group in df.groupby("user_id"):
        signals = {"crypto": 0, "property": 0, "lifestyle": 0, "anchor": 0, "exit": 0}
        last_date = None # CHATGPT FIX: Cleaner initialization

        for _, row in group.iterrows():
            current_date = row["timestamp"]
            delta_days = (current_date - last_date).days if last_date else 0

            if delta_days > 0:
                for key in signals:
                    signals[key] *= np.exp(-DECAY[key] * delta_days)

            bucket = BUCKET_MAP.get(row["event_type"])
            if bucket:
                signals[bucket] += np.log1p(row["amount"])

            # Note: total_score removed from tracking to prevent leakage
            history.append({
                "user_id": user_id, "timestamp": current_date,
                "crypto_sig": signals["crypto"], "property_sig": signals["property"],
                "anchor_sig": signals["anchor"], "exit_sig": signals["exit"],
                "lifestyle_sig": signals["lifestyle"]
            })
            last_date = current_date

    return pd.DataFrame(history)

# ---------------------------------------------------------
# LAYER 5: THE EXECUTIVE CHEF (The Credibility Layer Upgrade)
# ---------------------------------------------------------
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

def train_and_evaluate(df_scores, df_ground_truth):
    # THE UPGRADE: Extracting Consistency (mean) and Volatility (std)
    features = df_scores.groupby("user_id").agg({
        "crypto_sig": ["max", "mean"],
        "property_sig": ["max", "mean"],
        "anchor_sig": ["max", "count"],
        "exit_sig": ["max"],
        "lifestyle_sig": ["max", "std"] # Volatility check for Fake Whales
    })

    # Flatten columns (e.g., turns ('crypto_sig', 'max') into 'crypto_sig_max')
    features.columns = ['_'.join(col).strip() for col in features.columns.values]
    features = features.reset_index()

    # Fill NaNs (if a user only has 1 transaction, std is NaN)
    features = features.fillna(0)

    dataset = features.merge(df_ground_truth, on="user_id")
    dataset["target"] = dataset["is_high_value"].astype(int)

    # Automatically grab all the new credibility features
    feature_cols = [col for col in features.columns if col not in ["user_id", "target", "whale_since", "is_high_value"]]
    X = dataset[feature_cols]
    y = dataset["target"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    pos = sum(y_train == 1)
    neg = sum(y_train == 0)
    scale_weight = neg / pos if pos > 0 else 1

    model = XGBClassifier(
        n_estimators=100, max_depth=4, learning_rate=0.1,
        random_state=42, scale_pos_weight=scale_weight
    )
    model.fit(X_train, y_train)

    y_probabilities = model.predict_proba(X_test)[:, 1]
    precisions, recalls, thresholds = precision_recall_curve(y_test, y_probabilities)

    def get_metrics_for_recall(target_recall):
        idx = np.argmin(np.abs(recalls - target_recall))
        t = thresholds[idx] if idx < len(thresholds) else thresholds[-1]
        y_pred_custom = (y_probabilities >= t).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_test, y_pred_custom).ravel()
        return t, precisions[idx], recalls[idx], fp, tp

    modes = {
        "Aggressive (95% Catch)": get_metrics_for_recall(0.95),
        "Balanced (80% Catch)": get_metrics_for_recall(0.80),
        "Conservative (60% Catch)": get_metrics_for_recall(0.60)
    }

    importance = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
    return modes, precisions, recalls, importance

# ==========================================
# EXECUTION COMMANDS (The "Run" Button)
# ==========================================
print("1. Booting up the Matrix (Generating 9900 synthetic Dubai residents)...")
simulator = DubaiWealthSimulator(num_users=9900, days=365)
df_txns, df_truth = simulator.generate_data()

print("2. Running the Time-Decay Vector Radar...")
df_scores = compute_vector_score(df_txns)

print("3. Training the XGBoost Intelligence Engine...\n")
modes, precisions, recalls, importance = train_and_evaluate(df_scores, df_truth)

print("================================================================")
print("💰 THE BOARDROOM DASHBOARD: OPERATING MODES 💰")
print("================================================================")
print(f"{'MODE':<30} | {'RECALL (Caught)'} | {'PRECISION (Accuracy)'} | {'FALSE POSITIVES'} | {'TRUE WHALES'}")
print("-" * 85)

for mode_name, metrics in modes.items():
    t, p, r, fp, tp = metrics
    print(f"{mode_name:<30} | {r*100:>13.1f}% | {p*100:>18.1f}% | {fp:>15} | {tp:>11}")

print("\n==========================================")
print("🧠 WHAT DRIVES A DUBAI WHALE? (Feature Importance %)")
print("==========================================")
print((importance * 100).round(2).astype(str) + '%')

# Plotting the Curve
plt.figure(figsize=(8, 5))
plt.plot(recalls, precisions, marker='.', label='XGBoost Radar')
plt.xlabel('Recall (Catch Rate)')
plt.ylabel('Precision (Accuracy of Flags)')
plt.title('Precision-Recall Tradeoff Curve (Dubai Whales)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

print("\n[SYSTEM]: Pipeline Execution Complete.")